config/routes.rb
Dockyard::Application.routes.draw do

  resources :repositories

  get 'callback/github' => 'callback#github'

end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :repository

  STATUSES = ['queued', 'pulling', 'building', 'pushing', 'failed', 'complete']
  validates_inclusion_of :status, :in => STATUSES,
                         :message => "{{value}} must be in #{STATUSES.join ','}"

  after_initialize do
    if self.new_record?
      self.status = 'queued'
    end
  end

  def execute
    status = 'pulling'
    Shell.run repository.path, "git pull"
    status = 'building'
    Shell.run repository.path, "docker build -t #{repository.docker_uri} ."
    status = 'pushing'
    Shell.run repository.path, "docker push #{repository.docker_uri}"
    status = 'complete'
  end

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  has_many :builds

  def repos_path
    '/home/george/dockyard/repos'
  end

  def path
    "#{repos_path}/#{id}"
  end

  def initialise # not to be confused with initialize, the constructor
    Shell.run repos_path, "git clone #{repo_uri} #{id}"
    self.initialised = true
    save!
  end

  def build(tag)
    build = builds.create(tag: tag)
    build.execute
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController

  def github
    session[:github_token] = Github.new.get_token(params[:code]).token
    redirect_to new_repository_path
  end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  def index
    @repositories = Repository.all
  end

  def show
  end

  def new
    @repository = Repository.new

    github = Github.new oauth_token: session[:github_token]
    connected = !!session[:github_token]

    @github_auth_url = github.authorize_url redirect_uri: 'http://localhost:3000/callback/github?from=new', scope: 'repo'
    @repos = github.repos.list if connected

  end

  def edit
  end

  def create
    @repository = Repository.new(repository_params)

    if @repository.save
      redirect_to @repository, notice: 'Repository was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @repository.update(repository_params)
      redirect_to @repository, notice: 'Repository was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @repository.destroy
    redirect_to repositories_url, notice: 'Repository was successfully destroyed.'
  end

  private
    def set_repository
      @repository = Repository.find(params[:id])
    end

    def repository_params
      params.require(:repository).permit(:name, :repo_uri, :docker_uri)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dockyard" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Dockyard</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/repositories/_form.html.erb
<% if @repository.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@repository.errors.count, "error") %> prevented this repository from being saved:</h2>

    <ul>
    <% @repository.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
    <div class="form-group">
  <%= f.label :repo_uri %>
  <%= f.text_field :repo_uri, class: 'form-control' %>
</div>
    <div class="form-group">
  <%= f.label :docker_uri %>
  <%= f.text_field :docker_uri, class: 'form-control' %>
</div>
  

app/views/repositories/edit.html.erb
<h1>Edit repository</h1>

<%= form_for(@repository) do |f| %>
  <%= render 'form', f:f %>

  <div class="actions">
    <button class="btn btn-primary" type="submit">Save</button>
    <%= link_to 'Show', @repository,  class: 'btn btn-default' %>
    <%= link_to 'Back', repositories_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/repositories/index.html.erb
<h1>Repositories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Repo URI</th>
      <th>Docker URI</th>
      <th>Last build</th>
    </tr>
  </thead>

  <tbody>
    <% @repositories.each do |repository| %>
      <tr>
        <td><%= link_to repository.name, repository %></td>
        <td><%= repository.repo_uri %></td>
        <td><%= repository.docker_uri %></td>
        <td><%= repository.builds.where(status: 'complete').last.try(:created_at) || 'Never' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Repository', new_repository_path, class: 'btn btn-primary' %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= form_for(@repository) do |f| %>
  <%= render 'form', f:f %>

  <%= link_to 'Connect to GitHub', @github_auth_url unless @repos %>
  <% @repos.each do |repo| %>
    <%= repo.full_name %><br />
  <% end %>

  <div class="actions">
      <button class="btn btn-primary" type="submit">Save</button>
      <%= link_to 'Back', repositories_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @repository.name %></h1>

<p><%= link_to @repository.repo_uri, @repository.repo_uri %></p>

<h3>Builds</h3>

<table class="table">
    <thead>
    <tr>
        <th>Started at</th>
        <th>Tag</th>
        <th>Status</th>
    </tr>
    </thead>
    <tbody>
    <% @repository.builds.each do |build| %>
      <tr>
          <td><%= build.created_at %></td>
          <td><%= build.tag %></td>
          <td><%= build.status %></td>
      </tr>
    <% end %>
    </tbody>
</table>

<div class="actions">
  <h3>Actions</h3>
  <%= link_to 'Edit', edit_repository_path(@repository),  class: 'btn btn-default' %>
  <%= link_to 'Delete', @repository, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
  <%= link_to 'Back', repositories_path,  class: 'btn btn-default' %>
</div>